### ISSUE TITLE
tests would be nice

### ISSUE THREAD

**Issue by smoe** [mcfrith/tandem-genotypes#12]
There is not much to build, still, something to check the local installation with would be nice. Would you accept respective patches?

**Comment by mcfrith** [comment]
Thank you for your suggestions. Due to my inexperience, I have no clue what such patches would be like. I guess my answer would likely be "yes", but...

**Comment by smoe** [comment]
You are basically doing it already in your README, explaining what the output after processing your input files look alike. The difficulty is that nobody knows what the input looks like :)  I'd suggest a folder "example" or "test" to which you add this input data and also the output data for all your operations. And the test then is a diff between what a local installation gives and your reference.

I hope to generate such data myself over the next weeks, but I would not know if they are correct :)  I'll happily add the formal test scripts for your package if you would have the reference input and output data ready - maybe on another branch?

**Comment by mcfrith** [comment]
There's already a `tests` folder, with some input files, reference output `tests.out`, and `tests.sh` which runs the tests and does a diff. Is that fine, or are you suggesting something sightly different?

**Comment by smoe** [comment]
The tests folder is not shipping with the .tar.gz and I apologize for not having seen it in the git repo prior to submitting this issue. My suggestion would be to add it to the tarball with your next release.

Your "all-in-one" testing is a bit different but I like it. Many thanks!

**Comment by mcfrith** [comment]
Ok, we're on the same page now. Adding the tests would make the tarball much bigger (but not all that big, maybe I shouldn't care about it). I've vaguely seen suggestions on the internet to exclude such large tests. I thought bioconda also recommended that, but as I look again, it seems unclear. This is how it's tested in bioconda BTW: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/tandem-genotypes/meta.yaml

Overall, not sure whether to add the tests to the tarball...

**Comment by smoe** [comment]
I think you should not care about the size of the test directory. Anything below 50MB is just fine. Disk space is mostly a non-issue compared with the possibility/potential damage done by an incorrect computation because of some dependency changing the order of arguments of some function - the bioconda recipe just tests if --help works, right? This addresses the basic technical setup, but is not enough to help avoiding what would truly hurt. Nilesh, a Debian Med peer, downloaded your test directory separately, which is a bit beyond the routine of the average Debian packaging (https://lists.debian.org/debian-med/2021/07/msg00020.html), to properly complete the testing. So, Debian and certainly also Conda, would appreciate that test directory, I am very confident. Keeping it separate, well, it works as Nilesh has just proven, but also needs extra care and packaging skills and there are not so many Nileshs out there. If someone complains - blame me :)

**Comment by mcfrith** [comment]
Better late than never...
