### ISSUE TITLE
Obtain number of tandem repeats in reference

### ISSUE THREAD

**Issue by bpenaud** [mcfrith/tandem-genotypes#16]
Hello,

I would like to know if there is a way to obtain the number of tandem repeats in the reference ? Or a way to know the exact number of tandem repeats of the genotype (and not a difference between reference and genotype) ?

Thanks in advance,
Benjamin

**Comment by mcfrith** [comment]
I believe the number of repeats in the reference is:
(column3 - column2) / length(column4)
