### ISSUE TITLE
"the alignments are in the wrong order" before & after maf-sort

### ISSUE THREAD

**Issue by davidlougheed** [mcfrith/tandem-genotypes#17]
I'm getting the error `tandem-genotypes: error: the alignments are in the wrong order` when I run tandem-genotypes. I've ran the `.maf` file through `maf-sort` but the error persists. Any ideas on what could cause this?

**Comment by davidlougheed** [comment]
thanks for the prompt response!

the maf is generated with something like this:
```bash
bedtools bamtofastq -i "${bam}" -fq "${scratch}/${fq}"
last-train -P32 -Q0 hg38db "${scratch}/${fq}" > "${scratch}/${par}"
lastal -P32 -p "${par}" hg38db "${scratch}/${fq}" | last-split > "${scratch}/${maf}"
```
where bam/fq/par/maf are variables pointing to different files

the weird part of this workflow I guess is that I'm converting CCS reads from a BAM back to a fastq file; I've been able to do this with some individuals from the 1000Genomes dataset and now I'm trying it on HG002 from Genome in a Bottle.

**Comment by mcfrith** [comment]
That seems like it should work fine, and the alignments should be in the right order. Scratching my head...
* Did you run `lastdb` in a strange way?
* Could it be that 2 different reads get the same "name"?

By the way, this should sort them into the right order (though if 2 reads have the same name, we have bigger problems):

    maf-swap myfile.maf | maf-sort | maf-swap > out.maf

**Comment by davidlougheed** [comment]
lastdb was ran like this:
```bash
lastdb -P32 -uNEAR hg38db ./ref/hg38.analysisSet.fa
```

if the DB could cause it, it's possible that I need to regenerate it for GiaB's FASTA file – they are both hg38, but one might be slightly different I suppose. 

I'll take a look into those other possibilities as well!

**Comment by davidlougheed** [comment]
ah I found the issue - there do seem to be duplicates of each read in the FASTQ file for some reason, so I'll mark the issue as closed. thanks for all the help!

**Comment by mcfrith** [comment]
Thanks for sharing the solution!
