### ISSUE TITLE
tandem-genotypes-merge

### ISSUE THREAD

**Issue by VICTO160** [mcfrith/tandem-genotypes#21]
I keep running into an error when trying to run the merge option.  The for-loop at line 57 is causing this error: "ValueError: not enough values to unpack (expected 2, got 1)".

An example of the input line is: 
chr13   102813924       102814076       GAA     FGF14   .       -32     353     -33,-33,-32,-32,-32,-32,-32,-32,-32,-32,-32,-31,-29,341,342,343,344,344,350,354,357,398       -34,-33,-33,-32,-32,-32,-32,-32,-32,-32,-32,-32,-32,-32,-31,-31,350,353,353,353,354,354,355,356

**Comment by mcfrith** [comment]
Thanks for your interest in tandem-genotypes.
For merge, you need to first run tandem-genotypes with option `-v`.
The error message ought to be clearer...
