### ISSUE TITLE
Low coverage PB data

### ISSUE THREAD

**Issue by npatel22526** [mcfrith/tandem-genotypes#3]
Hello, 

Based on the  paper on [biorxiv](https://www.biorxiv.org/content/early/2018/06/27/356931.full.pdf+html) , the tool seems to be working well at 15x coverage. I have few samples sequence with Pacbio at 10x coverage . Do you have any experience with such low coverage data  ? If so, how well it works with it and if you have recommended parameters specific to low coverage long reads? 

Thanks, 
Nick

**Comment by mcfrith** [comment]
Hi Nick

I believe our paper includes a 6X Pacbio dataset (BAFME), which worked OK for us. So I'd recommend just the standard parameters.

For very large repeat expansions, the number of reads covering the whole expansion might be lower than the genome-wide coverage. So low coverage might be a problem for large repeats.

Have a nice day,
Martin
