### ISSUE TITLE
imperfect repeat unit

### ISSUE THREAD

**Issue by woodoo46** [mcfrith/tandem-genotypes#5]
Hi tandem-genotypes developers,

I just want to double check that if a repeat segment is made of two types of repeat units, the program still works well? For example, if a 168 repeat region has two types of repeat units TAGG and TACG, we supply the program either "chrom start end TAGG" or "chrom start end TACG"? And the result is the same?

Thanks.

George

**Comment by mcfrith** [comment]
Good question: tandem repeats can be tricky. I believe the result will indeed be the same, in this case.

The length of the repeat-unit affects tandem-genotypes, but the sequence of the repeat-unit has almost no effect, with just 2 exceptions:
* If the repeat-unit could encode poly-glutamine or -alanine and is in a protein-coding region, the "importance" is boosted, which changes only the order of output.
* If you supply a homopolymer (e.g. AAAA) as a "repeat-unit", it will be ignored by default, unless the -u option is changed.

Have a nice day,
Martin
