### ISSUE TITLE
different repeats at same location

### ISSUE THREAD

**Issue by ruligaolab** [mcfrith/tandem-genotypes#6]
Hello,  I noticed that the copy number counts are exactly same for two different repeats at same location. For instance, if two types of repeat acgttt and ccgtt at same location, the two line outputs are same.  I wonder how does the number of repeats are calculated? If the exact match of the repeat sequence is required?

**Comment by mcfrith** [comment]
Hello!
Exact match is not required, because it tries to allow for high rates of sequencing error.
The predicted copy number counts depend on the length of the repeat-unit, but not on its sequence.
The full details are in the paper mentioned at the end of the README.

**Comment by ruligaolab** [comment]
If I understand correct, that is to say, it can not tell apart two types of repeat in same loci.   Thank you.

**Comment by mcfrith** [comment]
If you'd like to examine the type of repeat (i.e. its sequence) in your data, `tandem-genotypes-merge` may be useful.
